// ** NOTE - THIS FILE IS AUTOMATICALLY GENERATED BY THE PNG TO C UTILITY

#include "..\resources\pngRes.h"

// Bitmap array
const unsigned int * pngBitmapLoc[] = {
PNG_TEST1,
PNG_TEST2,
PNG_TEST3,
};

#ifdef FULL_BUILD

// Bitmap X Size
const int pngBitXSize[] = {
10,
320,
320,
};

// Bitmap Y Size
const int pngBitYSize[] = {
10,
277,
277,
};

#else

// Bitmap X Size
const int pngBitXSize[] = {
1,
1,
1,
};

// Bitmap Y Size
const int pngBitYSize[] = {
1,
1,
1,
};

#endif

