// ** NOTE - THIS FILE IS AUTOMATICALLY GENERATED BY THE PNG TO C UTILITY


#pragma once
// Png Bitmap Information
extern const unsigned int * pngBitmapLoc[];
extern const int pngBitXSize[];
extern const int pngBitYSize[];

// Extern for each bitmap resource
extern const unsigned int PNG_TEST1[];
extern const unsigned int PNG_TEST2[];
extern const unsigned int PNG_TEST3[];

// Enum for each bitmap
typedef enum pngBitmapIndex {
TEST1,
TEST2,
TEST3,
} pngBitmapIndex;

