// ** NOTE - THIS FILE IS AUTOMATICALLY GENERATED BY THE BMP TO C UTILITY


// Bitmap information
extern const unsigned char * zgBitmapLoc[];
extern const int zgBitXSize[];
extern const int zgBitYSize[];

// Extern for each bitmap resource
extern const unsigned char BMP_FBATHEAT[];
extern const unsigned char BMP_RTRAFFICICON[];

// Enum for each bitmap
typedef enum zgBitmapIndex {
FBATHEAT,
RTRAFFICICON,
} zgBitmapIndex;

