// ** NOTE - THIS FILE IS AUTOMATICALLY GENERATED BY THE BMP TO C UTILITY

#include "..\resources\zgResources.h"

// Pointer to bitmap array
const unsigned char * zgBitmapLoc[] = {
BMP_FBATHEAT,
BMP_RTRAFFICICON,
};

// Bitmap X Size
const int zgBitXSize[] = {
88,
44,
};

// Bitmap Y Size
const int zgBitYSize[] = {
16,
96,
};

